# Generated by Django 5.1.7 on 2025-03-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
